version: '2'
services:
  postfix:
    image: untestedengineer/postfix-docker:latest
    expose:
    - "25"
    env_file:
      - .env
    restart: always
    volumes:
     - "/etc/localtime:/etc/localtime:ro"
