apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix
  namespace: example
  labels:
    app.kubernetes.io/instance: postfix
    app.kubernetes.io/name: postfix
    app.kubernetes.io/version: v1.0.1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: postfix
      app.kubernetes.io/name: postfix
      app: postfix
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: postfix
        app.kubernetes.io/name: postfix
        app.kubernetes.io/version: v1.0.1
        app: postfix
    spec:
      volumes:
        - name: secrets
          secret:
            secretName: postfix-auth-example
      containers:
      - name: postfix
        image: untestedengineer/postfix-docker:v1.0.1-alpine
        resources:
          limits:
            memory: "256Mi"
            cpu: "125m"
        env:
        - name: SMTP_SERVER
          value: "example.example.com"
        - name: SMTP_PORT
          value: "587" # 587 is necessary for some providers i 25 is blocked by some providers/ISPs
        - name: SMTP_NETWORKS
          value: "x.x.x.x/xx,y.y.y.y/yy" # Allowed network(s)/host(s) to relay through the application
        - name: SMTP_USERNAME_FILE
          value: "/secrets/smtp_username"
        - name: SMTP_PASSWORD_FILE
          value: "/secrets/smtp_password"  
        - name: SERVER_HOSTNAME
          value: "postfix.example.example.com"
        - name: DESTINATION
          value: "example.com"
        ports:
          - name: postfix 
            containerPort: 25
            protocol: TCP
        volumeMounts:
          - name: secrets
            mountPath: /secrets